const TYPES=['빈칸추론','주제','제목','요지','어법','어휘','문장삽입','순서배열','내용일치','서술형(단어배열)'];
const OBJ=new Set(TYPES.slice(0,9));
const CYCLES=[[3,1,5,2,4],[2,5,1,4,3],[5,2,4,1,3],[1,4,2,5,3],[4,1,3,5,2]];
const CIRC=['①','②','③','④','⑤'];
const $=s=>document.querySelector(s);
const E={wrap:$('#passagesContainer'),tpl:$('#passageTemplate'),book:$('#textbookName'),count:$('#passageCountText'),add:$('#addPassageBtn'),remove:$('#removePassageBtn'),reset:$('#resetBtn'),go:$('#generateBtn'),status:$('#statusPanel'),statusText:$('#statusText'),pct:$('#statusPercent'),bar:$('#progressBar'),results:$('#resultsSection'),list:$('#resultsContainer'),summary:$('#summaryStrip'),printExam:$('#printExamBtn'),printAns:$('#printAnswersBtn')};
const S={passages:[],results:[],busy:false};
const blank=()=>({passage:'',selectedTypes:['빈칸추론'],specs:{'빈칸추론':{count:1,difficulty:'보통'}}});
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const rich=v=>esc(v).replaceAll('&lt;u&gt;','<u>').replaceAll('&lt;/u&gt;','</u>').replaceAll('\n','<br>');
const clean=v=>String(v??'').replace(/^[①②③④⑤1-5.\s]+/,'').trim();
const total=p=>p.selectedTypes.reduce((n,t)=>n+Number(p.specs[t]?.count||0),0);
const norm=v=>{const s=String(v??'');for(let i=0;i<5;i++)if(s.includes(CIRC[i]))return String(i+1);return s.match(/[1-5]/)?.[0]||''};
function balanced(n){const a=[];let i=0;while(a.length<n)a.push(...CYCLES[i++%CYCLES.length]);return a.slice(0,n)}
function save(){localStorage.setItem('yms-moak-modify-draft',JSON.stringify({book:E.book.value,passages:S.passages}))}
function load(){try{const x=JSON.parse(localStorage.getItem('yms-moak-modify-draft')||'null');if(x?.passages?.length){S.passages=x.passages.slice(0,20);E.book.value=x.book||'2026 수능특강 영어';return}}catch{}S.passages=[blank(),blank()]}
function summaryCard(card,p){const n=total(p),pill=card.querySelector('.total-pill'),msg=card.querySelector('.card-message');pill.textContent=`총 ${n}문항`;pill.classList.toggle('over',n>10);msg.classList.toggle('error',!p.selectedTypes.length||n>10);msg.textContent=!p.selectedTypes.length?'문제 유형을 하나 이상 선택해주세요.':n>10?`현재 ${n}문항입니다. 지문당 최대 10문제로 줄여주세요.`:`이 지문에서 총 ${n}문제 생성 예정`}
function renderPassages(){E.wrap.innerHTML='';S.passages.forEach((p,idx)=>{const c=E.tpl.content.firstElementChild.cloneNode(true);c.querySelector('.passage-index').textContent=`PASSAGE ${String(idx+1).padStart(2,'0')}`;c.querySelector('.passage-title').textContent=`지문 ${idx+1} 세팅`;const ta=c.querySelector('.passage-input');ta.value=p.passage;ta.oninput=()=>{p.passage=ta.value;save()};const grid=c.querySelector('.type-grid');TYPES.forEach(t=>{const l=document.createElement('label');l.className='type-chip';l.innerHTML=`<input type="checkbox" ${p.selectedTypes.includes(t)?'checked':''}><span>${esc(t)}</span>`;l.querySelector('input').onchange=e=>{if(e.target.checked){if(!p.selectedTypes.includes(t))p.selectedTypes.push(t);p.specs[t]??={count:1,difficulty:'보통'}}else p.selectedTypes=p.selectedTypes.filter(x=>x!==t);save();renderPassages()};grid.append(l)});const specs=c.querySelector('.specs-list');p.selectedTypes.forEach(t=>{const sp=p.specs[t]??={count:1,difficulty:'보통'},r=document.createElement('div');r.className='spec-row';r.innerHTML=`<div class="spec-name">${esc(t)}</div><input class="count-input" type="number" min="1" max="5" value="${sp.count}"><select class="difficulty-select"><option ${sp.difficulty==='보통'?'selected':''}>보통</option><option ${sp.difficulty==='쉬움'?'selected':''}>쉬움</option><option ${sp.difficulty==='어려움'?'selected':''}>어려움</option></select>`;const n=r.querySelector('input'),d=r.querySelector('select');n.onchange=()=>{sp.count=Math.min(5,Math.max(1,Number(n.value)||1));n.value=sp.count;summaryCard(c,p);save()};d.onchange=()=>{sp.difficulty=d.value;save()};specs.append(r)});summaryCard(c,p);E.wrap.append(c)});E.count.textContent=`${S.passages.length}개`;E.add.disabled=S.busy||S.passages.length>=20;E.remove.disabled=S.busy||S.passages.length<=1}
function validate(){const empty=[],missing=[],over=[];S.passages.forEach((p,i)=>{if(!p.passage.trim())empty.push(i+1);if(!p.selectedTypes.length)missing.push(i+1);if(total(p)>10)over.push(i+1)});if(empty.length)throw Error(`지문 ${empty.join(', ')}이 비어있습니다.`);if(missing.length)throw Error(`지문 ${missing.join(', ')}의 문제 유형을 하나 이상 선택해주세요.`);if(over.length)throw Error(`지문 ${over.join(', ')}의 문항 수가 10개를 초과했습니다.`)}
function plans(){const n=S.passages.reduce((a,p)=>a+p.selectedTypes.reduce((b,t)=>b+(OBJ.has(t)?Number(p.specs[t].count):0),0),0),nums=balanced(n);let cur=0;return S.passages.map(p=>{const q=[];p.selectedTypes.forEach(t=>{const sp=p.specs[t];for(let i=0;i<sp.count;i++)q.push({type:t,difficulty:sp.difficulty,target_answer:OBJ.has(t)?nums[cur++]:null})});return{passage:p.passage.trim(),question_plan:q}})}
async function one(batch){const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(batch)}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`서버 오류 (${r.status})`);return j.questions||[]}
async function pool(items,limit,onDone){const out=new Array(items.length);let next=0,done=0;async function run(){while(true){const i=next++;if(i>=items.length)return;out[i]=await one(items[i]);onDone(++done,items.length)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return out}
function progress(done,all,text){const p=all?Math.round(done/all*100):0;E.status.classList.remove('hidden');E.statusText.textContent=text;E.pct.textContent=`${p}%`;E.bar.style.width=`${p}%`}
async function generate(){if(S.busy)return;try{validate();save();S.busy=true;E.go.disabled=true;E.results.classList.add('hidden');renderPassages();const b=plans(),qty=b.reduce((a,x)=>a+x.question_plan.length,0);progress(0,b.length,`총 ${qty}문항을 ${b.length}개 지문 단위로 출제 중입니다.`);const groups=await pool(b,4,(d,a)=>progress(d,a,`${d}/${a}개 지문 출제 완료 · 같은 지문은 API 1회로 처리합니다.`));S.results=groups.flat();if(!S.results.length)throw Error('생성된 문제가 없습니다.');progress(b.length,b.length,`총 ${S.results.length}문항 출제가 완료되었습니다.`);renderResults();E.results.classList.remove('hidden');E.results.scrollIntoView({behavior:'smooth'})}catch(e){progress(0,1,`오류: ${e.message||e}`);E.pct.textContent='!';E.bar.style.width='0%'}finally{S.busy=false;E.go.disabled=false;renderPassages()}}
function split(raw){raw=String(raw??'');if(!raw.startsWith('[주어진 문장]'))return{given:'',body:raw};const i=raw.indexOf('\n');return i<0?{given:raw.replace('[주어진 문장]','').trim(),body:''}:{given:raw.slice(0,i).replace('[주어진 문장]','').trim(),body:raw.slice(i+1).trimStart()}}
function resultCard(r,i){const {given,body}=split(r.passage),c=document.createElement('article');c.className='result-card';c.dataset.i=i;const opts=r.is_subjective?`<div class="sa-meaning"><strong>[우리말 해석]</strong> <span contenteditable data-field="sa_korean_meaning">${esc(r.sa_korean_meaning)}</span></div><div class="sa-box"><strong>&lt; 보 기 &gt;</strong><br><br><span contenteditable data-field="sa_given_words">${esc((r.sa_given_words||[]).join(' / '))}</span></div>`:`<div class="option-list">${(r.options||[]).map((o,k)=>`<div class="option-row"><span>${CIRC[k]||`${k+1}.`}</span> <span contenteditable data-option="${k}">${esc(clean(o))}</span></div>`).join('')}</div>`;c.innerHTML=`<div class="result-top"><div class="result-meta"><span class="q-badge">${i+1}</span><span class="meta-tag">${esc(r.question_type)}</span><span class="meta-tag">${esc(r.difficulty)}</span></div><span class="meta-tag">클릭해서 직접 수정 가능</span></div><div class="result-body"><p class="question-text"><strong>${i+1}. </strong><span contenteditable data-field="question_text">${esc(r.question_text)}</span></p>${given?`<div class="given-sentence"><strong>[주어진 문장]</strong><br><span contenteditable data-given>${rich(given)}</span></div>`:''}<div class="passage-box" contenteditable data-body>${rich(body)}</div>${opts}<details class="explanation"><summary>정답 및 해설 보기</summary><div class="explain-grid">${[['정답','correct_answer'],['출제 의도','intent'],['본문 근거','text_evidence'],['상세 해설','explanation'],['오답 분석 / 채점 기준','distractor_analysis'],['잦은 실수','common_mistakes']].map(([l,f])=>`<div class="explain-item"><strong>${l}</strong><span contenteditable data-field="${f}">${esc(r[f])}</span></div>`).join('')}</div></details></div>`;c.addEventListener('input',e=>{const el=e.target;if(el.dataset.option!==undefined){r.options[Number(el.dataset.option)]=el.textContent.trim();return}if(el.dataset.field==='sa_given_words'){r.sa_given_words=el.textContent.split('/').map(x=>x.trim()).filter(Boolean);return}if(el.dataset.field){r[el.dataset.field]=el.textContent.trim();return}if(el.hasAttribute('data-body')||el.hasAttribute('data-given')){const g=c.querySelector('[data-given]')?.innerText.trim()||'',b=c.querySelector('[data-body]')?.innerText.trim()||'';r.passage=g?`[주어진 문장] ${g}\n\n${b}`:b}});return c}
function renderResults(){const counts={'1':0,'2':0,'3':0,'4':0,'5':0};S.results.forEach(r=>{if(!r.is_subjective){const n=norm(r.correct_answer);if(n)counts[n]++}});E.summary.innerHTML=`<span class="summary-chip">총 ${S.results.length}문항</span>`+Object.entries(counts).map(([n,c])=>`<span class="summary-chip">${n}번 정답 ${c}개</span>`).join('');E.list.innerHTML='';S.results.forEach((r,i)=>E.list.append(resultCard(r,i)))}
function examHtml(){return S.results.map((r,i)=>{const {given,body}=split(r.passage),opts=r.is_subjective?`<div class="sa-meaning"><strong>[해석]</strong> ${esc(r.sa_korean_meaning)}</div><div class="sa-box">&lt; 보 기 &gt;<br>${esc((r.sa_given_words||[]).join(' / '))}</div><div class="answer-line"></div><div class="answer-line"></div>`:`<div class="options">${(r.options||[]).map((o,k)=>`<div>${CIRC[k]||`${k+1}.`} ${esc(clean(o))}</div>`).join('')}</div>`;return`<section class="question-block"><div class="question-row"><b>${i+1}.</b> ${esc(r.question_text)}</div>${given?`<div class="given"><b>[주어진 문장]</b><br>${rich(given)}</div>`:''}<div class="passage">${rich(body)}</div>${opts}</section>`}).join('')}
function print(kind){if(!S.results.length)return;const exam=kind==='exam',book=esc(E.book.value.trim()||'교재명 미입력'),content=exam?examHtml():S.results.map((r,i)=>`<section class="answer-block"><h3>${i+1}번 · ${esc(r.question_type)}</h3>${[['정답','correct_answer'],['출제 의도','intent'],['본문 근거','text_evidence'],['상세 해설','explanation'],['오답 분석 / 채점 기준','distractor_analysis'],['학생들의 잦은 실수','common_mistakes']].map(([l,f])=>`<div><b>${l}</b><p>${esc(r[f])}</p></div>`).join('')}</section>`).join(''),w=window.open('','_blank','noopener,noreferrer');if(!w)return alert('팝업이 차단되었습니다. 팝업을 허용해주세요.');w.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>YMS 모의고사</title><style>@page{size:A4;margin:12mm 10mm 14mm}*{box-sizing:border-box}body{margin:0;color:#000;font-family:"Malgun Gothic",sans-serif}.header{border-bottom:2px solid #111;padding-bottom:10px;margin-bottom:14px}.title{text-align:center;font-size:19pt;font-weight:900;letter-spacing:3px}.info{display:flex;justify-content:space-between;margin-top:9px;font-size:10pt}.columns{column-count:${exam?2:1};column-gap:9mm;column-rule:1px solid #ddd}.question-block,.answer-block{break-inside:avoid;page-break-inside:avoid;margin-bottom:13px;font-size:9.5pt;line-height:1.55}.question-row{font-weight:700;margin-bottom:7px}.given{border:1px solid #555;background:#f7f7f7;padding:7px 8px;margin-bottom:6px;font-family:"Times New Roman","Batang",serif}.passage{border:1px solid #333;padding:9px 10px;font-family:"Times New Roman","Batang",serif}.options{margin-top:7px;font-family:"Times New Roman","Batang",serif;display:grid;gap:3px}.sa-box{border:1px solid #888;text-align:center;margin-top:6px;padding:8px}.answer-line{height:21px;border-bottom:1px solid #aaa}.answer-block{border-bottom:1px dashed #aaa;padding-bottom:14px;font-size:10.5pt}.answer-block p{margin:2px 0 8px}.printbar{text-align:center;padding:8px;border-bottom:1px solid #ddd;margin-bottom:12px}.printbar button{border:0;background:#2457d6;color:#fff;border-radius:8px;padding:9px 18px;font-weight:700}@media print{.printbar{display:none}}</style></head><body><div class="printbar"><button onclick="window.print()">인쇄하기</button></div><header class="header"><div class="title">YMS 부송관 모의고사</div><div class="info"><span>교재 : ${book}</span><span>${exam?'이름 : __________________':'정답 및 해설'}</span></div></header><main class="columns">${content}</main></body></html>`);w.document.close()}
E.add.onclick=()=>{if(S.passages.length<20){S.passages.push(blank());save();renderPassages()}};E.remove.onclick=()=>{if(S.passages.length>1){S.passages.pop();save();renderPassages()}};E.reset.onclick=()=>{localStorage.removeItem('yms-moak-modify-draft');S.passages=[blank(),blank()];S.results=[];E.book.value='2026 수능특강 영어';E.results.classList.add('hidden');E.status.classList.add('hidden');renderPassages()};E.book.oninput=save;E.go.onclick=generate;E.printExam.onclick=()=>print('exam');E.printAns.onclick=()=>print('answers');load();renderPassages();
